using Emberline.Core;
using Emberline.Enemies;

namespace Emberline.Campaign
{
    /// <summary>
    /// The hundred missions. Every entry carries the ten fields the design rule
    /// requires; the last of them, the next-mission reason, is the one that
    /// stops the campaign being a menu of unrelated levels — each mission ends
    /// on the reason the next one begins.
    ///
    /// Renzo's state and the Seal's stage are set by mission band in Finish(),
    /// so the arc cannot drift entry by entry.
    /// </summary>
    public static partial class Campaign
    {
        private static GameplayType[] T(params GameplayType[] t) => t;
        private static EnemyKind[] K(params EnemyKind[] k) => k;
        private static string[] L(params string[] lines) => lines;

        private const GameplayType Combat = GameplayType.Combat, Stealth = GameplayType.Stealth,
            Investigation = GameplayType.Investigation, Rescue = GameplayType.Rescue,
            Defense = GameplayType.Defense, Escort = GameplayType.Escort, Chase = GameplayType.Chase,
            Exploration = GameplayType.Exploration, Survival = GameplayType.Survival,
            Boss = GameplayType.Boss, Sabotage = GameplayType.Sabotage, Memory = GameplayType.Memory,
            Conversation = GameplayType.Conversation, Endure = GameplayType.Endure;

        private const EnemyKind B = EnemyKind.Bandit, R = EnemyKind.Ranged, S = EnemyKind.Shade,
            C = EnemyKind.Chief, KG = EnemyKind.Kagachi, J = EnemyKind.Jin, H = EnemyKind.RaiderAxe,
            P = EnemyKind.PikeGuard, O = EnemyKind.Bomber, A = EnemyKind.Assassin,
            M_ = EnemyKind.Samurai, N = EnemyKind.RogueNinja, E = EnemyKind.EliteWarrior;

        private const EnvThemeId Village = EnvThemeId.Village, Forest = EnvThemeId.Forest,
            Bamboo = EnvThemeId.Bamboo, Mountain = EnvThemeId.Mountain, Temple = EnvThemeId.Temple,
            Castle = EnvThemeId.Castle, Fortress = EnvThemeId.Fortress, Graveyard = EnvThemeId.Graveyard,
            Burning = EnvThemeId.BurningVillage, Rainy = EnvThemeId.RainyBattlefield,
            Dawn = EnvThemeId.VillageDawn;

        private static CampaignMission M(int id, string name, GameplayType[] types, Region region,
            EnvThemeId theme, string purpose, string objective, string uniqueEvent, string discovery,
            string climax, string ending, string next, EnemyKind[] enemies = null, EnemyKind? boss = null,
            string foe = "", bool marsh = false, bool night = false, bool rain = false, bool snow = false,
            bool fog = false, string beat = "", string plan = "", string[] dialogue = null) => new()
        {
            id = id, name = name, types = types, region = region, theme = theme,
            storyPurpose = purpose, primaryObjective = objective, uniqueEvent = uniqueEvent,
            storyDiscovery = discovery, climax = climax, ending = ending, nextReason = next,
            enemies = enemies ?? System.Array.Empty<EnemyKind>(), boss = boss, foe = foe,
            marsh = marsh, night = night, rain = rain, snow = snow, fog = fog, beat = beat, plan = plan,
            dialogue = dialogue ?? System.Array.Empty<string>(),
        };

        public static readonly CampaignMission[] Missions = Finish(new[]
        {
            // =============================================================
            // ACT I — THE RETURN
            // CHAPTER 1 — ASHES OF YORUNE
            // =============================================================
            M(1, "FIRST BLOOD", T(Stealth, Exploration), Region.Ruins, Burning,
                "Renzo comes home to a village that no longer exists, and learns the people who burned it never left.",
                "Search the ruins of Yorune for any sign of who is still here.",
                "The first enemy has not noticed you: the game teaches the silent kill by giving you one for free, then takes the option away.",
                "Kagehira's forces are still operating around Yorune. This was not a raid that ended.",
                "A masked assassin drops from the burned watchtower and attacks Renzo in the open.",
                "In the assassin's coat: a map with one road marked in red. LANTERN ROAD.",
                "The map is the only lead there is. Renzo follows it before whoever drew it comes looking.",
                K(B, B, A), plan: "S01_FirstBlood",
                dialogue: L("RENZO|Ten years. They kept the fires going ten years.",
                            "RENZO|Somebody is still here. Somebody is still looking for something.")),

            M(2, "THE LANTERN ROAD", T(Rescue, Stealth, Chase), Region.Ruins, Village,
                "The road on the map carries an enemy convoy, and the convoy carries people.",
                "Shadow the convoy along the Lantern Road without being seen, and free whoever is in the wagons.",
                "A moving patrol: the guards walk a route rather than stand a post, and the wagons stop where the lanterns are.",
                "The prisoners were being taken north, toward the marsh. Nobody has said why.",
                "The Convoy Captain turns back for his cargo and meets Renzo on the road.",
                "A document in the captain's saddlebag names something called the Black Seal.",
                "Kagehira is spending soldiers and wagons on a seal. Renzo needs to know why, and the camp the convoy came from will.",
                K(B, P, R), foe: "convoycaptain", night: true,
                dialogue: L("RENZO|Nine wagons. No grain. No steel.",
                            "RENZO|They are carrying people.")),

            M(3, "EYES IN THE DARK", T(Stealth, Investigation), Region.Ruins, Village,
                "The camp the convoy came from is where the orders come from.",
                "Get into the enemy camp, read what they are looking for, and get out.",
                "Vision is short and the rain covers you; archers on the roofs are the threat, not the men on the ground.",
                "Someone named Goro is commanding the search. Every order carries his mark.",
                "The alarm goes up. The way out is a run through a camp that is now awake.",
                "The last order on the table: Goro is closing the northern pass tonight.",
                "If the pass closes, the prisoners' trail closes with it. Renzo goes north before Goro can shut the door.",
                K(A, R, R, B), night: true, rain: true, plan: "S03_EyesInTheDark"),

            M(4, "THE BROKEN GATE", T(Combat), Region.Mountains, Castle,
                "The road north runs through a checkpoint that was built to stop exactly one man.",
                "Reach the northern checkpoint and break through the gate.",
                "The soldiers say Renzo's family name before he has said a word. They were told to expect a Kurogawa.",
                "Kagehira's soldiers know the name Kurogawa. They have known it for years.",
                "An elite guard holds the gate alone and does not need help.",
                "The gate falls. On the far side, a man in a toll-captain's armour is waiting and unhurried. Goro.",
                "Goro has come himself. There is no road around him, only through.",
                K(P, P, H, E)),

            M(5, "GORO'S TOLL", T(Boss, Rescue), Region.Mountains, Castle,
                "The first named enemy, and the first proof that the search has a purpose.",
                "Defeat Goro.",
                "A boss who talks while he fights: every phase break, Goro says one more thing he should not.",
                "Goro says Renzo's sister may have survived the night Yorune burned.",
                "Goro, in a barricaded post, with nowhere for either of them to go.",
                "The prisoner ledger at the post carries a name Renzo has not heard spoken in ten years. AIKO KUROGAWA.",
                "Aiko is alive, or was. The trail the prisoners took is the only way to find out which.",
                K(P, H, R, B, B), boss: C, plan: "S04_GorosToll",
                dialogue: L("GORO|The Kurogawa boy. You have your father's stance and none of his sense.",
                            "RENZO|Say her name again.",
                            "GORO|Which one? The ledger has so many.")),

            M(6, "THE MISSING GIRL", T(Investigation, Chase), Region.Forest, Village,
                "The first mission with no enemies for its opening minute: Renzo is reading the ground, not clearing it.",
                "Find and follow the prisoner trail north from Goro's post.",
                "Tracking: drag marks, a dropped lantern, a scrap of cloth, each one further from the road than the last.",
                "Aiko was transported north with a smaller group, split off from the rest.",
                "An enemy patrol finds Renzo on the trail and the hunt reverses.",
                "The trail leaves the road and enters the black pines.",
                "The forest is where the trail goes. Renzo follows it in.",
                K(A, N, R), plan: "S05_SerpentsTrail"),

            M(7, "BLACK PINES", T(Stealth), Region.Forest, Forest,
                "The forest belongs to the rogues, and it is thick enough to hide either side.",
                "Cross the black pines without being caught.",
                "Dense cover cuts both ways: enemies lose you at twelve paces, and you lose them at the same.",
                "Enemy camps in the forest are not looking for Renzo. They are searching for the Black Seal.",
                "An ambush in the thickest of the pines, from three sides.",
                "Cut into a trunk at the forest's edge: an old symbol. Renzo knows it. It was on his father's blade.",
                "A Yorune mark in a forest Yorune never reached. Renzo needs to know who cut it and when.",
                K(N, N, R, R, O)),

            M(8, "FATHER'S MARK", T(Exploration, Investigation), Region.Forest, Bamboo,
                "The first time the story turns from Kagehira to Renzo's own family.",
                "Follow the old marks and find out what Renzo's father was doing here.",
                "Environmental clues only: no document tells you anything, the marks do.",
                "Renzo's father knew about the Black Seal, years before Yorune burned.",
                "A samurai patrol, disciplined and patient, on the one path the marks lead down.",
                "The marks end at a cairn. Under it, a route drawn by a hand Renzo recognises, pointing into the marsh.",
                "His father walked into the marsh on purpose. Renzo takes the same route.",
                K(M_, M_, R)),

            M(9, "INTO THE FOG", T(Survival), Region.Marsh, Graveyard,
                "The marsh is where the story stops being about soldiers.",
                "Cross the marsh entrance and survive what lives in it.",
                "You cannot see. Standing still and listening is a mechanic, not a mood.",
                "Enemy soldiers in the marsh talk about an old temple, and about not going near it after dark.",
                "An attack on the enemy camp at the edge of the fog, with things that are not soldiers joining in.",
                "Through the fog, lanterns. Dozens of them. A temple.",
                "The temple is what the soldiers fear and what his father's route pointed to. Renzo goes to it.",
                K(A, R, O, S, S), marsh: true, fog: true, plan: "S06_IntoTheReeds"),

            M(10, "THE OLD TEMPLE", T(Combat, Exploration), Region.Temples, Temple,
                "The chapter's payoff: the Seal is not Kagehira's. It is Renzo's.",
                "Enter the ruined temple and find what Kagehira's men are afraid of.",
                "The temple comes down around the fight: the last stage is an escape through a collapsing hall.",
                "The Black Seal is bound to Renzo's family. The temple carvings show a Kurogawa holding it.",
                "Elite warriors in the temple's heart, then the ceiling.",
                "Renzo walks out of the dust with a fragment of the seal in his hand.",
                "One fragment means there are others, and Kagehira is collecting. Renzo follows his supply lines to find where.",
                K(M_, E, E, S), marsh: true),

            // =============================================================
            // CHAPTER 2 — THE LANTERN NETWORK
            // =============================================================
            M(11, "THE SUPPLY ROUTE", T(Sabotage, Stealth), Region.Villages, Village,
                "The first look at the size of what Kagehira is building.",
                "Track the enemy supply route and burn the wagon at the end of it.",
                "Sabotage: the fire takes time to set, and the guards come back while it does.",
                "Kagehira is not hunting a seal with a raiding party. He is building an army.",
                "The supply wagon burns and its escort arrives to find it burning.",
                "Three soldiers survive and run. Renzo lets them.",
                "Running men go home. Renzo follows them to wherever that is.",
                K(B, B, R, P)),

            M(12, "SILENT CARGO", T(Stealth), Region.Villages, Village,
                "A shipment moving at night has something to hide.",
                "Intercept the night shipment without waking the escort.",
                "A silent elimination challenge: every guard can be taken unseen, and every alarm costs the objective.",
                "The cargo is weapons, from four different provinces. Kagehira is buying from everyone.",
                "The last guard is awake, armed, and standing on the crate.",
                "A bill of lading with a supplier's name and a village Renzo has never heard of.",
                "Somebody is selling Kagehira steel by the wagon. The village on the bill is the supplier.",
                K(A, A, B, R), night: true),

            M(13, "THE BROKEN VILLAGE", T(Investigation, Exploration), Region.Villages, Burning,
                "Yorune was not the only village that burned.",
                "Search the destroyed settlement for what happened to it.",
                "The village tells the story without a line of dialogue: the homes, the carts, the notices.",
                "This village was searching for the Seal too. Kagehira burned it for the same reason.",
                "The Scavenger King, who has made the ruin his own.",
                "Under the elder's floor: a second map, older than the first, with the marsh temple marked.",
                "The elder's house held more than a map. Someone who lived there is still alive.",
                K(B, B, H, R), foe: "raiderleader"),

            M(14, "THE SURVIVOR", T(Escort, Defense), Region.Villages, Village,
                "The first living person who remembers Aiko.",
                "Protect the last survivor of the village until the road is clear.",
                "Waves come from every side while she walks; the fight moves with her.",
                "The survivor remembers Aiko. She was alive after the fire, and she was not alone.",
                "An enemy elite arrives to finish the village.",
                "Safe, the survivor tells Renzo about a road that does not appear on any map.",
                "A hidden road is how the enemy moves unseen. Renzo takes it.",
                K(B, P, R, B, E)),

            M(15, "HIDDEN ROAD", T(Stealth), Region.Forest, Forest,
                "The secret route is watched, which is how Renzo knows it matters.",
                "Follow the hidden road without being seen.",
                "Traversal under watch: the archers are above the road, not on it.",
                "The route ends at an enemy watchtower that sees the whole valley.",
                "Getting into the tower's shadow without a shot being fired.",
                "The tower is lit. Someone is on the top of it.",
                "The tower watches every road Renzo could take. It has to come down.",
                K(A, A, R, R)),

            M(16, "WATCHFIRE", T(Combat, Defense), Region.Forest, Castle,
                "Taking the enemy's eyes.",
                "Capture the watchtower and hold it.",
                "Vertical assault, then a reversal: once the tower is yours, you are the one being attacked.",
                "The maps in the tower show three enemy territories, and a fourth marked only with a serpent.",
                "Holding the tower against its own reinforcements.",
                "The signal fire is Renzo's now. He lets it burn, so they will come to him.",
                "Three territories, and the marsh route between them. A messenger will know which one matters.",
                K(R, R, M_, P, B)),

            M(17, "THE MESSENGER", T(Chase), Region.Forest, Forest,
                "The enemy's words travel on foot.",
                "Intercept the messenger before he reaches the border.",
                "A moving duel: the target runs, fights, runs again.",
                "The messenger carries orders sealed by Kagehira himself.",
                "The last stretch, where the messenger stops running and turns.",
                "The orders are in a cipher Renzo does not know. Yet.",
                "A cipher needs a key, and the messenger came from a post that has one.",
                K(B, B, N, R)),

            M(18, "DEAD LETTER", T(Investigation, Stealth), Region.Villages, Village,
                "What Kagehira wants, in his own words.",
                "Get into the relay post and decode the orders.",
                "The investigation is the mission: three pieces of the key, hidden in a post full of assassins.",
                "Kagehira is looking for someone called 'the daughter.'",
                "Assassins between Renzo and the last piece of the key.",
                "'Find the daughter. She knows where he hid it.' There is only one daughter this could mean.",
                "If Kagehira has been searching for Aiko, his prisoner records will say where he looked.",
                K(A, A, A, R), night: true),

            M(19, "THE DAUGHTER", T(Stealth, Investigation), Region.Villages, Castle,
                "Confirmation.",
                "Infiltrate the records house and find the prisoner rolls.",
                "The alarm is inevitable here: the records are in the one room you cannot leave quietly.",
                "Confirmed: Aiko Kurogawa was imprisoned, alive, six years ago.",
                "The escape after the alarm, with the roll under Renzo's coat.",
                "The roll says where she was held. It does not say where she is.",
                "The enemy's communication towers pass every transfer order. The second tower has hers.",
                K(P, P, R, B, A)),

            M(20, "THE SECOND LANTERN", T(Sabotage, Defense), Region.Villages, Castle,
                "The enemy's second signal tower, and the first time Kagehira hears Renzo's name.",
                "Destroy the enemy's second communication tower.",
                "Two towers, two routes: whichever you light first, the other is ready for you.",
                "The tower's log names Aiko's transfer to the silent forest.",
                "Tower destruction, then the elite squad sent to keep it standing.",
                "As the tower burns, a rider brings its last message: 'KUROGAWA IS COMING.' They know.",
                "Kagehira knows Renzo's name and where he is. The forest is between them.",
                K(R, R, P, A, N, E), plan: "S08_TwinLanterns", night: true),

            // =============================================================
            // CHAPTER 3 — THE SILENT FOREST
            // =============================================================
            M(21, "THE HUNTER", T(Endure, Stealth), Region.Forest, Forest,
                "The chapter opens with Renzo as prey.",
                "Survive the thing hunting you and get out of its ground.",
                "A foe you cannot beat yet: something pale in the trees that does not die when cut, and lets you live when the clock runs out.",
                "The hunter is not Kagehira's. It was here before him.",
                "The hunter circles closer with every minute, and the forest goes silent around it.",
                "It withdraws. It was measuring him.",
                "Something in the forest is hunting Renzo for its own reasons. The only way through is to leave no trail.",
                K(A, N, S), foe: "paleshade", night: true, fog: true),

            M(22, "NO FOOTPRINTS", T(Stealth), Region.Forest, Bamboo,
                "Pure stealth: the mission the alarm ends.",
                "Infiltrate the forest camp and leave without a footprint.",
                "No combat is required at all. Every kill is optional and every one of them is loud.",
                "The camp holds transfer orders with Aiko's name, three weeks old.",
                "The last patrol crosses the only exit as the clock runs down.",
                "Renzo leaves the camp exactly as he found it, minus one document.",
                "The orders route Aiko through a clearing to the north. Somebody died there.",
                K(A, R, R, N)),

            M(23, "BLOOD ON SNOW", T(Investigation), Region.Snow, Mountain,
                "An assassination Renzo did not commit.",
                "Investigate the killing in the clearing.",
                "First snow: tracks stay, and so does blood. Used once, and it is the mission.",
                "The dead man was one of Kagehira's own officers, killed by his own side.",
                "The killers return to clean the scene and find Renzo in it.",
                "The officer's last letter: he had refused to take a child north.",
                "Three assassins did this, and they are between Renzo and the road north.",
                K(A, A, H, P), snow: true),

            M(24, "THE THREE BLADES", T(Boss, Combat), Region.Forest, Forest,
                "Three elite assassins who fight as one.",
                "Defeat the Three Blades.",
                "A triple duel: three assassins share one set of tactics, and the last one changes hers.",
                "The Blades were sent for Renzo specifically. Someone above Goro is paying attention.",
                "The last Blade, alone, faster than the other two together.",
                "A silk cord from the last Blade's wrist: the mark of the forest camp's master.",
                "The camp that sent them is the camp that has the rest of the orders.",
                K(A, A, A, N), foe: "threeblades"),

            M(25, "THE SILENT CAMP", T(Sabotage, Stealth), Region.Forest, Bamboo,
                "The perfect infiltration.",
                "Destroy the enemy camp without triggering the alarm.",
                "Sabotage under silence: the fire must be set in three places while the camp sleeps.",
                "The camp's commander was hunting the Black Seal, not Renzo. Renzo is a complication.",
                "The third fire, in the commander's own tent.",
                "The camp burns without a bell rung. Renzo watches it from the trees.",
                "The commander's route led into a fog-bound forest path. Renzo takes it before dawn.",
                K(A, N, R, B, B), night: true),

            M(26, "THE BLIND PATH", T(Survival), Region.Forest, Forest,
                "The forest at its worst.",
                "Navigate the fog-covered path to the far side of the forest.",
                "Fog and listening again, deeper: the enemies here are silent until they are close.",
                "The forest path is marked with red thread, tied to branches at a child's height.",
                "Everything that was following in the fog arrives at once.",
                "The thread runs out at a clearing. Someone tied it here on purpose.",
                "Red thread. Aiko's bracelet was red thread. Renzo follows it.",
                K(S, S, A, N), fog: true),

            M(27, "THE RED THREAD", T(Investigation), Region.Forest, Bamboo,
                "The first thing of Aiko's that Renzo touches in ten years.",
                "Follow the red thread to its end.",
                "A quiet mission almost to the end: the discovery is the point, the fight is the cost.",
                "The thread ends at a bead from Aiko's bracelet. She was here, and she left it on purpose.",
                "The men who took her came back for the bead.",
                "Renzo ties the bead into his own wrist.",
                "Aiko was leaving a trail. Where it points next is where she was taken.",
                K(B, A, R)),

            M(28, "THE DECOY", T(Rescue), Region.Forest, Forest,
                "The enemy knows what Renzo is looking for now.",
                "Reach the reported location and rescue the girl.",
                "The rescue is a trap: the prisoner is not Aiko, and the pen is bait.",
                "The enemy staged Aiko's location. They are using her to catch him.",
                "The trap springs: the pen's walls were the ambush.",
                "The girl in the pen has never heard of Aiko. Renzo frees her anyway.",
                "Whoever laid the trap will lay another. Renzo turns the hunt around.",
                K(A, A, R, N, P)),

            M(29, "THE HUNTER'S TRAP", T(Survival), Region.Forest, Forest,
                "Surrounded.",
                "Survive until there is a way out.",
                "The arena closes: every wave comes from a different side and the exits shut one by one.",
                "The assassins answer to something they call the Pale Shade.",
                "The last exit, and the thing standing in it.",
                "The forest goes quiet. It has arrived.",
                "There is no leaving the forest without going through what owns it.",
                K(A, N, S, S, O, P)),

            M(30, "PALE SHADE", T(Boss), Region.Forest, Graveyard,
                "The chapter boss, and the thing that hunted Renzo in mission 21.",
                "Defeat the Pale Shade.",
                "A boss that is not wholly there: it dissolves and reforms, and the fight is about where it will be, not where it is.",
                "The Pale Shade knows where Aiko went. It is what the marsh sends when it wants to know things.",
                "The Shade at its full form, in the dark.",
                "Dying, it tells him: 'She was moved. To the toll-captain's country.'",
                "Aiko was transferred to Goro's territory. Renzo goes to war with Goro.",
                K(S, S, A), foe: "paleshade", night: true, fog: true,
                dialogue: L("PALE SHADE|…you carry her thread… she carried yours…",
                            "RENZO|Where is she.",
                            "PALE SHADE|…where the toll is paid…")),

            // =============================================================
            // ACT II — THE HUNT
            // CHAPTER 4 — GORO'S TERRITORY
            // =============================================================
            M(31, "THE FORTRESS ROAD", T(Exploration), Region.Mountains, Castle,
                "Goro's country announces itself.",
                "Approach Goro's territory along the fortress road.",
                "Banners: every hundred paces, a serpent. The road is a statement.",
                "Goro has fortified the whole valley. This is not a toll post any more.",
                "The road's first garrison, which does not intend to let anyone pass.",
                "From the ridge: prisoner wagons, moving in a line toward the fortress.",
                "The wagons carry people. Renzo goes down to them.",
                K(P, P, H, R)),

            M(32, "PRISONER WAGONS", T(Rescue, Chase), Region.Mountains, Castle,
                "The first rescue that is about more than one person.",
                "Rescue the villagers from the wagons before they reach the fortress.",
                "The wagons are moving: free who you can while the escort fights and the drivers whip on.",
                "The prisoners are from a dozen villages. Goro has been emptying the valley.",
                "The last wagon, the escort's captain, and a road that is running out.",
                "The freed villagers speak of the camps: not prisons, pens.",
                "There are camps. Renzo has the location of the nearest.",
                K(B, P, R, H, A)),

            M(33, "BROKEN CHAINS", T(Sabotage, Rescue), Region.Mountains, Fortress,
                "Destroy the machine, not just its output.",
                "Free the prisoner camp and burn it.",
                "Two pens, two guard rotations: the second wakes when the first goes quiet.",
                "A camp record lists Aiko's transfer out, two months ago, to 'the execution ground.'",
                "The camp commander, an axe raider, in the burning yard.",
                "The camp is ash and the prisoners are gone into the hills.",
                "'Execution ground' is not a place Renzo can leave for tomorrow.",
                K(P, H, H, R, B)),

            M(34, "THE EXECUTION GROUND", T(Defense, Rescue), Region.Mountains, Fortress,
                "The chapter's most urgent mission.",
                "Stop the execution.",
                "A clock the player cannot see: the executioner walks the line, and each prisoner reached is lost.",
                "Aiko is not among them. The ledger says she was moved again, the night before.",
                "Holding the platform against Goro's men while the last prisoners are cut loose.",
                "Everyone on the platform lives. None of them is her.",
                "Goro moved her. Goro's army knows where. Renzo goes through it.",
                K(H, R, A, M_, E)),

            M(35, "GORO'S ARMY", T(Combat), Region.Mountains, Castle,
                "The first large, organised force.",
                "Break the squad Goro has sent to end this.",
                "A real formation: pikes in front, archers behind, and an officer who calls the changes.",
                "The squad carries orders to bring Renzo in alive. Kagehira wants to talk.",
                "The officer's last stand when the formation breaks.",
                "The squad is finished. Its officer will not say who wanted Renzo alive, but the seal on the order is a serpent.",
                "An army needs a smith. Renzo finds where Goro's steel is made.",
                K(P, P, P, R, R, M_)),

            M(36, "THE BLACKSMITH", T(Escort, Rescue), Region.Mountains, Village,
                "The man who made the enemy's weapons was never on their side.",
                "Rescue the blacksmith and get him out of Goro's reach.",
                "An escort who fights: the smith swings a hammer, and he is not fast.",
                "The smith forged the Three Blades' steel and marked every blade he made under duress.",
                "Goro's riders reach the road before the smith does.",
                "Safe, the smith gives Renzo the mark: every blade he made for them can be told from an honest one.",
                "Goro will answer the loss of his smith by burning the village that hid him.",
                K(B, B, R, H, A)),

            M(37, "THE SIEGE", T(Defense), Region.Villages, Burning,
                "The one time the player defends a place that matters.",
                "Defend the village from Goro's forces until they break.",
                "Multiple gates: each wave picks a different one, and the village's walls fail in sequence.",
                "Goro's forces are under orders to burn every village between here and the marsh.",
                "The last gate, the last wave, and Goro's banner in the field beyond.",
                "The village stands. Goro's banner does not advance. It waits.",
                "Goro has stopped sending men. He is coming himself.",
                K(B, B, P, R, H, A, E)),

            M(38, "THE HUNTER RETURNS", T(Endure, Chase), Region.Mountains, Mountain,
                "Goro, unleashed.",
                "Survive Goro's hunt and reach the mountain road.",
                "The boss is the pursuer: Goro cannot be beaten here, only outlasted and outrun.",
                "Goro is hunting Renzo against Kagehira's orders. He wants this personally.",
                "Goro at the ridge, and the drop behind Renzo.",
                "Goro lets him run. He wants the fight on his own ground.",
                "Goro's ground is the mountain gate. Renzo goes to it.",
                K(H, P, R), foe: "goro"),

            M(39, "THE MOUNTAIN GATE", T(Combat, Sabotage), Region.Mountains, Fortress,
                "Goro's last wall.",
                "Break through the mountain fortress gate.",
                "The gate has to be burned open while the wall shoots down at you.",
                "Inside the gatehouse: Aiko's cell, empty, with her thread on the bars.",
                "The gatehouse garrison, then the gate.",
                "The gate falls. Goro is waiting in the yard, alone, sword drawn.",
                "There is nothing between Renzo and Goro now.",
                K(P, P, R, R, H, E)),

            M(40, "GORO'S END", T(Boss), Region.Mountains, Fortress,
                "The final duel with the first enemy.",
                "Defeat Goro.",
                "A boss the player already beat once, fighting like a man who learned from it.",
                "Goro took Aiko deeper into the marsh on Kagehira's orders, to a temple under the water.",
                "Goro's last phase, without his guard, without his pride.",
                "Goro dies on his own gate. 'The marsh,' he says. 'She's under it.'",
                "Under the marsh. Renzo goes back into the fog.",
                K(P, H, R), boss: C, night: true,
                dialogue: L("GORO|Twice, Kurogawa. Nobody gets me twice.",
                            "RENZO|Then tell me where she is, and it will only be once.")),

            // =============================================================
            // CHAPTER 5 — INTO THE MARSH
            // =============================================================
            M(41, "THE DROWNED ROAD", T(Survival), Region.Marsh, Graveyard,
                "The ground itself is the enemy.",
                "Cross the flooded road before the tide closes it.",
                "The water rises twice while you are standing in it.",
                "The carts on the road were untouched except for their lanterns. Somebody is collecting light.",
                "The last stretch, in rising water.",
                "The far bank, and voices in the fog that are not soldiers.",
                "The voices are coming from the fog ahead. Renzo goes to find who is making them.",
                K(P, P, R, A, B, S), marsh: true, plan: "S07_DrownedRoad"),

            M(42, "VOICES IN THE FOG", T(Investigation), Region.Marsh, Graveyard,
                "The marsh speaks.",
                "Find the source of the voices in the fog.",
                "The voices move: each clue is where a voice was, not where it is.",
                "The voices are prisoners, calling from a camp the marsh has half swallowed.",
                "The shades that have been answering the voices.",
                "The camp is under the water line. So are its records.",
                "Sunken records mean sunken answers. Renzo goes into the camp.",
                K(S, S, S, A), marsh: true, fog: true),

            M(43, "THE SUNKEN CAMP", T(Investigation, Survival), Region.Marsh, Graveyard,
                "What the water kept.",
                "Search the submerged enemy camp.",
                "Half the arena is underwater; the search is in the shallows, and the deep is not safe.",
                "The camp's last commander wrote that the 'daughter' had been moved to the temple 'for the key.'",
                "The thing in the deep water that has been watching the search.",
                "A key. Aiko is not a prisoner. She is a lock.",
                "The temple wants her for something. The marsh hunters between here and it want Renzo.",
                K(S, S, O, A), marsh: true),

            M(44, "MARSH HUNTERS", T(Survival), Region.Marsh, Graveyard,
                "The assassins have followed Renzo into the fog.",
                "Survive the assassin ambush.",
                "An ambush in fog: the enemy is closer than you can see and so are you.",
                "The assassins were sent by Jin Kurogane, not by Goro. A new name.",
                "The last assassins, when the fog thins and both sides can see.",
                "A Kurogane crest on the last body. Renzo has heard the name. He does not know why it stings.",
                "An enemy patrol went into the fog before Renzo and did not come out. What stopped them might stop him.",
                K(A, A, A, N, R), marsh: true, fog: true),

            M(45, "THE MISSING PATROL", T(Exploration, Investigation), Region.Marsh, Graveyard,
                "Even the enemy is afraid of the marsh.",
                "Find the enemy patrol that disappeared.",
                "The clues are bodies, and what killed them is still here.",
                "The patrol was killed by the marsh's own guardians: shades that answer to no warlord.",
                "The thing that killed the patrol, when Renzo reaches the last of them.",
                "Reed smoke on the wind. Somebody lives out here.",
                "Someone survives in this marsh. They will know how to reach the temple.",
                K(S, S, S, S), marsh: true, fog: true),

            M(46, "THE REED VILLAGE", T(Defense, Exploration), Region.Marsh, Village,
                "People who chose the marsh over Kagehira.",
                "Reach the reed village and earn its trust.",
                "The villagers are hostile at first; the defense that follows is what turns them.",
                "The village hides an old guide who has been to the temple and returned.",
                "The village attacked by shades, with Renzo the only blade.",
                "The guide agrees to take him. She does not agree to like it.",
                "The guide knows the way. The way is not safe, and she is not fast.",
                K(S, S, A, R), marsh: true),

            M(47, "THE OLD GUIDE", T(Escort), Region.Marsh, Graveyard,
                "Someone else's life in Renzo's hands, on ground that wants both of them.",
                "Protect the guide to the temple stair.",
                "An escort through the marsh: the guide stops for nothing, and the water rises behind her.",
                "The guide knew Renzo's father. He came this way ten years ago, with something wrapped in cloth.",
                "The temple stair, and everything in the marsh that does not want it climbed.",
                "The guide sits down on the stair and will go no further. 'Below,' she says. 'It's all below.'",
                "The ruin is under the water. Renzo goes down.",
                K(S, S, B, R, A), marsh: true, fog: true, plan: "S02_LanternRoad"),

            M(48, "BENEATH THE WATER", T(Survival, Exploration), Region.Temples, Temple,
                "Under the marsh.",
                "Enter the submerged ruin.",
                "The water is the clock: the ruin floods behind you and the way in becomes the way not-out.",
                "The ruin is Kurogawa work. The carvings are the same hand as the symbol in the pines.",
                "The flood reaches the chamber door as the last guardian falls.",
                "The door. Sealed. Marked with the symbol from his father's blade.",
                "The chamber is the Seal's. Renzo has the fragment that opens it.",
                K(S, S, S, E), marsh: true),

            M(49, "THE SEAL CHAMBER", T(Investigation, Exploration), Region.Temples, Temple,
                "The chapter's revelation, found rather than told.",
                "Discover the Black Seal chamber and what it holds.",
                "No enemies until the chamber is read; the fight comes for what you learned.",
                "The Seal is not a weapon. It is a lock with three keys, and Renzo's father made the keys.",
                "The chamber's guardians wake when the first key is lifted.",
                "The first key, in Renzo's hand, and the chamber going dark.",
                "One key of three. The second is wherever his father hid it, and his father's journal will say.",
                K(E, M_, S, O), marsh: true, night: true),

            M(50, "THE FIRST KEY", T(Combat, Survival), Region.Temples, Temple,
                "Kagehira's men arrive for what Renzo already holds.",
                "Escape the chamber with the first key.",
                "Escape under pursuit: the chamber's own defences turn on the intruders, both sides.",
                "Renzo's father hid the Seal from Kagehira deliberately, at the cost of Yorune.",
                "The chamber stair, with the marsh above and Kagehira's elite below.",
                "Renzo surfaces with the key. Behind him, the temple closes.",
                "His father's journal is the map to the second key. It is in the drowned temple's upper halls.",
                K(E, M_, A, A, R), marsh: true,
                dialogue: L("RENZO|He hid it. He hid it and they burned the village for it.",
                            "RENZO|Father. What did you do.")),

            // =============================================================
            // CHAPTER 6 — THE DROWNED TEMPLE
            // =============================================================
            M(51, "FATHER'S JOURNAL", T(Investigation), Region.Temples, Temple,
                "The past, in his father's hand.",
                "Recover his father's journal from the temple's upper halls.",
                "The journal is in pieces across the halls; each page read changes what Renzo sees.",
                "The journal begins the year before Yorune burned. His father knew Kagehira was coming.",
                "The temple's watchers, when the last page is lifted.",
                "The last page is a date. The night Yorune burned. And a place to stand.",
                "The journal asks him to remember. The memory is where the truth is.",
                K(S, S, M_), marsh: true),

            M(52, "THE LAST NIGHT", T(Memory, Exploration), Region.Villages, Dawn,
                "Renzo walks through the night Yorune burned, as he remembers it.",
                "Play through the memory of Yorune's last evening.",
                "A memory mission: the village whole, the people alive, and the player walking through it knowing.",
                "The evening was ordinary. His father was not: he was packing something wrapped in cloth.",
                "The first fire, on the ridge, as the memory ends.",
                "Renzo wakes on the temple floor with the journal open to the next page.",
                "The memory stopped at the fire. The next page is the fire.",
                beat: "memory_lastnight"),

            M(53, "THE BURNING VILLAGE", T(Combat, Memory), Region.Villages, Burning,
                "What actually happened.",
                "Fight through the burning village as it was.",
                "The village burns in real time around the memory; the enemies are the ones who were there.",
                "The raiders were not raiding. They were searching every house for one thing.",
                "The house where his father made his stand.",
                "The memory breaks at the door. Renzo could not go in then. He cannot now.",
                "His father's stand is the page he has never been able to read.",
                K(B, B, H, R), beat: "memory_burning"),

            M(54, "THE SWORDMASTER", T(Boss, Memory), Region.Villages, Burning,
                "His father's final stand, as the journal tells it.",
                "Learn how Renzo's father fell.",
                "The player fights as the memory of his father: stronger, slower, and doomed.",
                "His father held the door long enough for the Seal to be carried out. He did not hold it for himself.",
                "The raider captain — a young Goro — at the door.",
                "The door holds. The man behind it does not.",
                "The Seal was carried out by someone. The journal says who.",
                K(B, P, A), foe: "goro"),

            M(55, "MOTHER'S CHOICE", T(Escort, Memory, Rescue), Region.Villages, Burning,
                "His mother, and the people she saved.",
                "Play through his mother's escape with the villagers.",
                "An escort through fire, with a child at the head of the line.",
                "His mother carried the Seal out of Yorune. She gave it to the child to hold.",
                "The lantern line, and the raiders waiting at the end of it.",
                "The villagers reach the ridge. His mother turns back for the last child.",
                "The child at the head of the line was Aiko. The memory follows her.",
                K(B, R, R, O)),

            M(56, "AIKO", T(Stealth, Memory), Region.Villages, Burning,
                "Aiko's last hour of freedom.",
                "Play Aiko's escape until it fails.",
                "The player is Aiko: no sword, no strength, only stealth and a village she knows better than they do.",
                "Aiko hid the Seal before she was taken. She never told them where.",
                "The raiders find her in the shrine. She has already hidden it.",
                "The memory ends with a hand over her mouth and a thread snapping.",
                "The Seal was never taken. Aiko hid it, and Kagehira has spent ten years asking her where.",
                K(B, A, N), beat: "memory_aiko"),

            M(57, "THE PRISONER", T(Investigation), Region.Temples, Temple,
                "Back in the present: Aiko's cell in the temple.",
                "Find the cell Aiko was held in.",
                "The temple's prison wing, read cell by cell; hers is the one with the thread.",
                "Aiko was held here for years. She scratched the second key's location into the wall in a code only a Kurogawa could read.",
                "The wardens, who have been told to let no one read the walls.",
                "Renzo reads his sister's handwriting for the first time in ten years.",
                "The second key is under the temple's guardian. The wall says so.",
                K(P, P, R, M_), marsh: true, night: true),

            M(58, "THE SECOND KEY", T(Rescue, Combat), Region.Temples, Temple,
                "The second of three.",
                "Recover the second Seal key.",
                "The key is in the flooded nave; the water is chest-deep and the enemies do not care.",
                "Kagehira's men found this chamber years ago and could not open it. Only a Kurogawa can.",
                "The nave's last guard, waist-deep.",
                "Two keys. The guardian below is what stands between him and the third.",
                "The Drowned Guardian holds the way down. It was put there by his father.",
                K(S, S, E, M_), marsh: true),

            M(59, "THE DROWNED GUARDIAN", T(Boss), Region.Temples, Temple,
                "The elite fight of the chapter, with his father's mark on it.",
                "Defeat the Drowned Guardian.",
                "A guardian bound to the family: it holds back when Renzo bleeds, and hits harder when he does not.",
                "The guardian was set by his father to keep the third key from anyone — including his own children.",
                "The guardian's last phase, in the dark, in the water.",
                "It falls. Under it: not a key. A message.",
                "His father left words instead of a key. The words say why.",
                K(S, S), foe: "drownedguardian", marsh: true, night: true),

            M(60, "THE TRUTH BENEATH YORUNE", T(Conversation, Exploration), Region.Temples, Temple,
                "The mid-campaign revelation.",
                "Read what his father left beneath Yorune.",
                "No fight. The mission is the walk to the message and the walk back, changed.",
                "Kagehira did not burn Yorune for revenge or conquest. He wanted the Black Seal, and Renzo's father refused him.",
                "The message ends with a name: the man who told Kagehira where the Seal was. Kurogane.",
                "Renzo surfaces. He has stopped looking for answers. He is looking for Kurogane.",
                "Jin Kurogane sold Yorune. Renzo goes to find him.",
                marsh: true, beat: "father_message"),

            // =============================================================
            // CHAPTER 7 — KUROGANE
            // =============================================================
            M(61, "THE BLACK BLADE", T(Endure), Region.Villages, Rainy,
                "The first meeting with Jin.",
                "Survive the first encounter with Jin Kurogane.",
                "Jin cannot be beaten here. He can be hurt, and he notices.",
                "Jin knows Renzo's name, his father's, and his sister's. He says them like a man reading a list.",
                "Jin, unhurried, taking the fight apart.",
                "Jin steps back into the rain. 'Not yet,' he says.",
                "Jin walked away over the rooftops. Renzo does not let him.",
                K(A, A, R), foe: "jin", rain: true, night: true,
                dialogue: L("JIN|Kurogawa. You have your father's stance.",
                            "RENZO|You are the second man to say that. The first is dead.",
                            "JIN|The first was not me.")),

            M(62, "THE PURSUIT", T(Chase), Region.Villages, Rainy,
                "The rooftop chase.",
                "Chase Jin across the rooftops.",
                "A chase against a target who fights back at every ledge and never fully runs.",
                "Jin is leading Renzo somewhere. The chase is his choice, not Renzo's.",
                "The last roof, the drop, and Jin waiting on the far side of it.",
                "Renzo makes the jump. Jin is already sheathing his sword.",
                "Jin stopped running because he wanted to fight here. Renzo obliges him.",
                K(N, N, A, R), rain: true),

            M(63, "NO HONOR", T(Endure), Region.Villages, Castle,
                "Renzo loses.",
                "Fight Jin.",
                "A duel the player is meant to lose: Jin defeats Renzo, and does not kill him.",
                "Jin could have killed him twice. He chose not to, and he wanted Renzo to know it.",
                "Renzo on his knees, and Jin's blade at his throat, withdrawn.",
                "'Go home, Kurogawa. There is nothing up this mountain but me.'",
                "Jin let him live, and Renzo does not know why. His past will.",
                K(M_, A), foe: "jin", night: true, beat: "jin_mercy"),

            M(64, "THE FALLEN SOLDIER", T(Investigation, Stealth), Region.Villages, Village,
                "Who Jin was.",
                "Investigate Jin's past in the garrison town.",
                "Investigation among people who knew Jin as a hero.",
                "Jin was Kagehira's finest officer and left the army the year Yorune burned.",
                "Jin's old unit, still loyal, when they realise what Renzo is asking.",
                "A portrait in the garrison hall: Jin, ten years younger, standing behind Renzo's father.",
                "Jin and his father knew each other. Jin's men will know how.",
                K(A, A, P, R)),

            M(65, "KUROGANE'S MEN", T(Combat), Region.Villages, Castle,
                "Jin's personal unit.",
                "Fight Jin's personal unit.",
                "Elite soldiers who fight like Jin taught them: they read heavies and they never block twice the same way.",
                "Jin's men were at Yorune. Every one of them.",
                "The unit's captain, who was Jin's second that night.",
                "The captain says only: 'He tried to stop it.'",
                "A man who fights honestly can be asked honestly. Renzo challenges Jin to a duel with terms.",
                K(M_, M_, E, A, R)),

            M(66, "THE DUELIST", T(Boss), Region.Villages, Village,
                "Pure combat, on agreed terms.",
                "Win the duel with Jin's champion.",
                "A formal duel: no allies, no interference, a ring drawn in the dust.",
                "Jin will not fight until Renzo has beaten his champion. He is testing something.",
                "The champion, a ronin who fights exactly like Jin.",
                "The champion yields. Jin was watching from the roofline.",
                "Jin has seen enough. He sends a message: a place, a time, and no guards.",
                K(M_), foe: "finalcommander"),

            M(67, "THE BROKEN MASK", T(Exploration), Region.Villages, Village,
                "Jin's connection to Yorune.",
                "Search Jin's old house for what he kept.",
                "An empty house that is the whole mission; every room is a clue.",
                "Jin's family was from Yorune. He left it the year before it burned, to serve Kagehira.",
                "The men Kagehira sent to burn the house before Renzo could read it.",
                "In the ashes of the last room: a mask, broken in half, one half missing.",
                "Half a mask, and the other half is on Jin's face. He is waiting where he said.",
                K(A, A, N, R), night: true),

            M(68, "THE CONFESSION", T(Conversation, Survival), Region.Villages, Rainy,
                "Jin tells the truth.",
                "Meet Jin and hear him out.",
                "The fight is optional and short; the conversation is the mission.",
                "Jin witnessed Yorune's destruction. He told Kagehira where the Seal was, and then he tried to stop what came.",
                "Kagehira's assassins interrupt the confession.",
                "'I gave him the map. I did not give him the village. He took that himself.'",
                "Jin has one more thing to say, and he will only say it with a sword in his hand.",
                K(A, A, A, R), rain: true, beat: "jin_confession"),

            M(69, "LAST WARNING", T(Endure, Conversation), Region.Villages, Castle,
                "Jin's warning, and the question the last act is built on.",
                "Hear Jin's warning and survive what he does to prove it.",
                "Jin fights to show, not to win: every exchange is a lesson about what Renzo is becoming.",
                "'If you reach Kagehira, you may become him.' Jin has watched it happen before.",
                "Jin's final demonstration: Renzo's own rage, used against him.",
                "Jin sheathes his sword. 'Tomorrow, then. Properly.'",
                "Tomorrow. The duel neither of them can walk away from.",
                K(M_), foe: "jin", night: true, beat: "jin_warning"),

            M(70, "KUROGANE", T(Boss), Region.Villages, Rainy,
                "The late-game boss, and the death that changes Renzo.",
                "Defeat Jin Kurogane.",
                "A duel against the one enemy who fights with honour: no adds, no tricks, and a phase that is only the two of them breathing.",
                "Jin tells him, dying: Aiko is alive, held inside Kagehira's mountain fortress.",
                "Jin's last phase, all storm.",
                "Jin dies with the half mask in his hand. 'Do not become him.'",
                "Aiko is in the mountain fortress. Renzo begins the climb.",
                K(), boss: J, rain: true, night: true,
                dialogue: L("JIN|You came. Good. I did not want to die in bed.",
                            "RENZO|You could walk away.",
                            "JIN|I did that once. It burned a village.")),

            // =============================================================
            // ACT III — THE END
            // CHAPTER 8 — THE IRON FORTRESS
            // =============================================================
            M(71, "THE MOUNTAIN ROAD", T(Exploration), Region.Snow, Mountain,
                "The ascent begins.",
                "Begin the climb to Kagehira's fortress.",
                "Snow and thin air: the road is the enemy as much as the men on it.",
                "The road is littered with the enemy's own dead. The mountain is killing Kagehira's men.",
                "The first garrison of the ascent, in a blizzard.",
                "Above, the glow of a camp with artillery in it.",
                "The camp above holds the guns that cover the road. They have to fall.",
                K(P, H, R, A), snow: true),

            M(72, "THE FROZEN CAMP", T(Sabotage), Region.Snow, Mountain,
                "Taking the guns.",
                "Destroy the artillery and supply camp.",
                "Fires set in the cold burn slow, and the powder carriers know it.",
                "The camp's supplies were meant for a siege. Kagehira expects an army, not one man.",
                "The magazine, when the last fire reaches it.",
                "The camp goes up. The mountain shivers.",
                "The explosion has loosened the slope above the road. Renzo has minutes.",
                K(O, O, P, R, H), snow: true, night: true),

            M(73, "THE AVALANCHE", T(Survival, Chase), Region.Snow, Mountain,
                "The mountain comes down.",
                "Escape the collapsing route.",
                "The arena collapses behind the player: there is one direction, and the clock is the mountain.",
                "Kagehira's men are caught in it too. The ones who survive stop fighting each other's enemies.",
                "The last stretch, with the snow at Renzo's heels.",
                "The outer wall, out of the white.",
                "The wall is the fortress. There is no more road.",
                K(A, R, S), snow: true, fog: true),

            M(74, "THE OUTER WALL", T(Combat, Defense, Boss), Region.Fortresses, Fortress,
                "Assault, defense and a boss in one mission.",
                "Assault the fortress wall and hold the breach.",
                "Three roles in sequence: take the gate, hold it, then face the man who comes to retake it.",
                "The wall's commander wears Yorune steel. The smith's mark is on it.",
                "The breach held, and the commander in it.",
                "The wall is Renzo's. The inner fortress is not.",
                "The inner fortress has one silent way in, and the wall's plans show it.",
                K(P, P, R, R, H, E, E), foe: "ironguard", snow: true),

            M(75, "THE SILENT GATE", T(Stealth), Region.Fortresses, Fortress,
                "The quiet way in.",
                "Infiltrate the inner fortress through the drain.",
                "The fortress asks how you want to play it, once, at the gate, and holds you to it.",
                "The fortress armoury is full of Yorune steel. Every blade belonged to someone on the missing list.",
                "Two elites and archer support at the inner gate.",
                "Inside. The prison tower is lit.",
                "Aiko is in the tower. Renzo climbs.",
                K(E, E, P, P, R), snow: true, night: true, plan: "S09_SerpentsGuard"),

            M(76, "THE PRISON TOWER", T(Rescue, Stealth), Region.Fortresses, Fortress,
                "The rescue that has been ten years coming.",
                "Search the prison tower for Aiko.",
                "Every cell freed is a voice that might be hers. None of them is.",
                "The prisoners say the girl with the thread was moved last night.",
                "The tower's wardens, and the alarm they are trying to reach.",
                "Her cell, at the top, empty. Warm.",
                "An empty cell has a record. The record will say where.",
                K(P, P, A, R), night: true),

            M(77, "THE EMPTY CELL", T(Investigation), Region.Fortresses, Fortress,
                "The near miss.",
                "Find where Aiko was taken.",
                "The investigation is fought: the evidence is in rooms the guards are burning.",
                "Aiko was moved to the inner fortress, to Kagehira himself. He has all three keys' worth of reasons.",
                "The records room, on fire, with the transfer order in it.",
                "The order is in Kagehira's own hand. She is with him.",
                "Kagehira's elite guard stands between the outer fortress and the warlord's hall.",
                K(A, A, P, R, H)),

            M(78, "THE IRON GUARD", T(Boss, Combat), Region.Fortresses, Fortress,
                "Kagehira's shield.",
                "Fight through Kagehira's elite guard.",
                "The Iron Guard fight as a unit with a captain who calls the changes; take the captain and the unit breaks.",
                "The Iron Guard were Goro's men once. They know exactly who Renzo is.",
                "The captain of the guard, in the iron hall.",
                "The guard is broken. The inner gate is ahead, and the last commander.",
                "One commander remains between Renzo and the hall.",
                K(E, E, E, M_, R), foe: "ironguard"),

            M(79, "THE INNER GATE", T(Boss), Region.Fortresses, Fortress,
                "The last commander.",
                "Defeat the final commander.",
                "The commander fights with the Three Blades' discipline and Goro's strength: everything the campaign has taught, at once.",
                "The commander was told Renzo would reach this gate. Kagehira has been expecting him for months.",
                "The commander's last stand at the gate itself.",
                "The gate opens. The hall beyond is lit, and empty.",
                "The throne hall. Whatever is in it is what all of this was for.",
                K(M_, M_, E, R), foe: "finalcommander"),

            M(80, "THE WARLORD'S HALL", T(Exploration), Region.Stronghold, Castle,
                "The end of the approach, and the wrong person on the throne.",
                "Reach the throne chamber.",
                "The hall is empty of soldiers and full of what Kagehira has collected: every lantern from the drowned road.",
                "Kagehira is gone. He left the fortress before Renzo took the wall.",
                "The hall's last defenders, and a figure behind the throne who is not one of them.",
                "Aiko. Standing. Older. Alive.",
                "She is here, and Kagehira is not. Whatever he wants, he left her to tell it.",
                K(E, E, A, R), night: true),

            // =============================================================
            // CHAPTER 9 — THE BLACK SEAL
            // =============================================================
            M(81, "YOU CAME", T(Conversation, Exploration), Region.Stronghold, Castle,
                "The reunion.",
                "Find Aiko in the hall.",
                "No enemies. The mission is the walk across the hall.",
                "Aiko has been Kagehira's prisoner for ten years and his prize for the last one. She knows what the Seal is.",
                "Aiko turns. 'You came.'",
                "Two words, and ten years.",
                "Aiko has a story that will take the night to tell. The fortress is not safe to tell it in.",
                beat: "you_came",
                dialogue: L("AIKO|You came.",
                            "RENZO|I said I would.",
                            "AIKO|You were nine.")),

            M(82, "THE LONG NIGHT", T(Defense, Conversation), Region.Stronghold, Castle,
                "What happened to Aiko.",
                "Hold the hall while Aiko tells it.",
                "A conversation interrupted by waves: every lull is another piece of the story.",
                "Aiko hid the Seal the night Yorune burned. Kagehira has spent ten years asking her where, and she has never told him.",
                "The last wave, and the doors giving.",
                "'It is under the shrine floor. He never thought to look at home.'",
                "The Seal is in Yorune, and Kagehira's army stands between here and there. First, Aiko has to survive the fortress.",
                K(P, P, R, A, E), beat: "long_night"),

            M(83, "THE PRISONER", T(Escort), Region.Stronghold, Fortress,
                "Aiko out of the fortress.",
                "Escort Aiko through the fortress.",
                "Aiko can run and Aiko can hide; she cannot fight, and she will not wait.",
                "Kagehira's soldiers hesitate at Aiko. Some of them were at Yorune.",
                "The last courtyard, and the soldiers who did not hesitate.",
                "Outside the walls. Behind them, the fortress erupts in its own fighting.",
                "The fortress is fighting itself. Renzo needs to know why.",
                K(P, A, R, B, H, E)),

            M(84, "THE BETRAYAL", T(Combat), Region.Stronghold, Fortress,
                "The army turns.",
                "Survive the fortress mutiny and find who is leading it.",
                "Enemy soldiers turn against Kagehira mid-fight: the last waves are fighting each other, and then they stop.",
                "Half the army has turned. They followed Kagehira for conquest, not for a seal.",
                "The loyalists' last stand, and the mutineers standing down at the sight of Aiko.",
                "The mutineers open the way to the ancient chamber under the fortress.",
                "The chamber under the fortress is where Kagehira kept the keys. Aiko knows the door.",
                K(P, P, H, R, A, E), night: true),

            M(85, "THE SEAL'S DOOR", T(Exploration), Region.Seal, Temple,
                "The door.",
                "Reach the ancient chamber with Aiko.",
                "Aiko reads the chamber as they walk; the clues are hers, not Renzo's.",
                "The chamber was built by the first Kurogawa. It was never Kagehira's to open.",
                "The chamber's guardians, awake for the first time in a century.",
                "The door, and their father's mark on it, and a message beneath the mark.",
                "Their father left words at the door. They are for both of them.",
                K(S, S, E), night: true),

            M(86, "FATHER'S FINAL MESSAGE", T(Memory, Conversation), Region.Seal, Temple,
                "His father's last word.",
                "Hear their father's final message.",
                "A memory neither of them has: their father, alone, the night before, speaking to children who were not there yet.",
                "Their father knew Kagehira would come, and hid the Seal so that no one — including his children — would open it in anger.",
                "The message ends: 'Whatever it is you are angry about when you hear this — be less.'",
                "Aiko takes Renzo's hand. He lets her.",
                "The message says what the Seal is not. Aiko knows what it is.",
                beat: "father_final"),

            M(87, "THE MEANING OF THE SEAL", T(Investigation), Region.Seal, Temple,
                "What it is.",
                "Assemble the truth of the Seal from the chamber's carvings.",
                "The investigation is the chamber itself; the fight is Kagehira's men arriving to stop it being read.",
                "The Black Seal is not a weapon. It is a key: to the mountain's water, and every village below it.",
                "Kagehira's vanguard in the chamber, ordered to take Aiko alive.",
                "Kagehira has the third key. He has had it for a year. He needs the door, and the door needs a Kurogawa.",
                "Kagehira is coming to the chamber himself, and he is not coming alone.",
                K(E, E, A, R, M_)),

            M(88, "KAGEHIRA'S TRUTH", T(Endure, Conversation), Region.Seal, Fortress,
                "The warlord, in his own words.",
                "Face Kagehira and hear his reasons.",
                "Kagehira does not fight to win here. He talks, and every sentence is a cut.",
                "Kagehira's obsession: with the Seal, he controls every village's water. Without it, he is a bandit with an army.",
                "Kagehira's demonstration of what he can do without the Seal.",
                "He withdraws to raise his army. 'Open it, or I will burn my way to the summit and open it with your sister's hands.'",
                "Kagehira's army is marching on the fortress. There is one night to prepare.",
                K(E, E), foe: "kagachi", night: true, beat: "kagehira_truth"),

            M(89, "THE FINAL MARCH", T(Defense), Region.Seal, Fortress,
                "The siege of the fortress.",
                "Hold the fortress against Kagehira's army.",
                "The mutineers hold the walls with Renzo; the waves are the largest in the game and the last.",
                "Kagehira's army is breaking on the walls. He does not care. He is not with it.",
                "The final wave, and the realisation that Kagehira is already inside.",
                "The walls hold. The chamber does not.",
                "Kagehira went around the army. He is at the door with the third key.",
                K(B, B, P, P, R, R, H, A, E, E), night: true),

            M(90, "THE DOOR OPENS", T(Chase), Region.Seal, Temple,
                "The chamber opens.",
                "Reach the chamber before Kagehira opens it.",
                "A chase against a door: the clock is the ritual, and the enemies are the ones guarding it.",
                "Kagehira has Aiko's blood on the key. He does not need her willing.",
                "The door opens as Renzo reaches it. Kagehira takes the final key and goes up.",
                "The chamber is open. Kagehira has all three keys and a road to the summit.",
                "The summit is where the Seal's lock is. Kagehira is climbing to it.",
                K(E, E, M_, A, R), night: true),

            // =============================================================
            // CHAPTER 10 — THE SERPENT'S END
            // =============================================================
            M(91, "THE BURNING FORTRESS", T(Chase, Survival), Region.Seal, Burning,
                "The fortress falls.",
                "Get Aiko out of the collapsing fortress.",
                "The fortress burns and falls around the escape; the exits close in the order the fire chooses.",
                "Kagehira set the fire himself. He is burning the bridge behind him.",
                "The last gate, and the fire reaching it first.",
                "Out. The summit road, and Kagehira's rear guard on it.",
                "The road to the summit is held by the last of Kagehira's army.",
                K(A, R, E, S), night: true),

            M(92, "THE LAST ARMY", T(Combat), Region.Snow, Mountain,
                "The remaining forces.",
                "Fight through Kagehira's remaining army.",
                "The largest sustained fight in the game, with the mutineers arriving at the end.",
                "The army is fighting for pay. The mutineers are fighting for Aiko. It shows.",
                "The last officer, and the mutineers breaking the line behind him.",
                "The road is open. The summit is a day's climb.",
                "The summit is where Kagehira is. Renzo climbs.",
                K(P, P, P, R, R, H, H, A, E), snow: true),

            M(93, "THE SUMMIT ROAD", T(Exploration), Region.Snow, Mountain,
                "The climb.",
                "Climb toward Kagehira.",
                "Thin air and a blizzard: the mission is endurance, and the enemies are the ones who could not keep up.",
                "Kagehira's guard died on this road. He climbed on alone.",
                "The final ascent, and the last of the guard turning back to hold it.",
                "The summit gate, and Kagehira's strongest warriors in front of it.",
                "Kagehira's best are at the gate. They are the last wall.",
                K(A, R, S, S), snow: true, fog: true),

            M(94, "THE FINAL GUARD", T(Boss, Combat), Region.Snow, Fortress,
                "Kagehira's strongest.",
                "Defeat Kagehira's strongest warriors.",
                "Every named foe's tactics, in one unit: they read, they punish, they protect, they retreat.",
                "The final guard were told Renzo would kill Kagehira. They were told to make sure he did not arrive whole.",
                "The last two, back to back, in the snow.",
                "The gate is open. Beyond it, the summit, and nothing on it.",
                "Kagehira is on the summit. He has seen Renzo coming for an hour.",
                K(E, E, E, M_, M_, N), foe: "ironguard", snow: true),

            M(95, "THE SERPENT'S SHADOW", T(Endure), Region.Seal, Mountain,
                "Kagehira strikes first.",
                "Survive Kagehira's ambush.",
                "The warlord as an ambusher: he attacks from the fog and vanishes, and the arena is his.",
                "Kagehira is faster than Renzo expected, and he does not want to kill him yet.",
                "Kagehira's blade at Renzo's back, and the cut he chooses not to make.",
                "'Alone,' he says. 'Come alone.' Aiko is gone from Renzo's side.",
                "Kagehira has Aiko. Renzo goes up alone, as he was told.",
                K(S, S, A), foe: "kagachi", fog: true, night: true),

            M(96, "NO WAY BACK", T(Combat, Survival), Region.Seal, Mountain,
                "Alone.",
                "Fight alone to the summit chamber.",
                "No allies, no mutineers, no Aiko; the last of the shades and the last of the men, together.",
                "Kagehira has released everything the marsh made. The shades were his all along.",
                "The chamber stair, with everything he has left on it.",
                "The chamber door, and a voice inside it Renzo knows.",
                "Kagehira wants to talk before the end. Renzo lets him.",
                K(S, S, S, S, A, E), night: true),

            M(97, "FATHER AND SON", T(Conversation, Defense), Region.Seal, Temple,
                "The final truth.",
                "Hear what Kagehira knows about Renzo's father.",
                "The revelation, then the fight it starts.",
                "Renzo's father and Kagehira were brothers-in-arms. The Seal was entrusted to both. One kept faith.",
                "Kagehira's guard, when Renzo refuses the offer.",
                "'Your father chose the villages. I chose the future. One of us was right, boy. Let us find out which.'",
                "There is nothing left to say. The chamber is open and Kagehira is in it.",
                K(E, E, M_), night: true, beat: "father_and_son"),

            M(98, "THE BLACK SEAL", T(Combat, Exploration), Region.Seal, Temple,
                "The chamber, opened.",
                "Enter the opened Seal chamber.",
                "The chamber is a place the player has only seen carved: now it is real, and the water is rising in it.",
                "The Seal was never meant to be opened. It was meant to be guarded. Kagehira has opened it.",
                "The chamber's last guardians, awake, on both sides.",
                "Kagehira, at the Seal, waiting. Aiko beside him, unbound. She has not run.",
                "Kagehira is standing at the Seal. This is the end of it.",
                K(S, S, E, E), night: true),

            M(99, "KAGACHI", T(Boss), Region.Seal, Temple,
                "The final boss.",
                "Defeat Kagehira.",
                "Four phases — swordsman, warlord, collapsing arena, exhausted duel — and a choice: the execution is offered and refused.",
                "Kagehira staggered, on his knees. Renzo raises the sword. Aiko: 'Don't become like them.' He lowers it.",
                "Kagehira's last attack, from his knees, and Renzo's answer.",
                "Kagehira dies. Renzo's sword is lowered. He did not become him.",
                "It is over. The only thing left is to leave.",
                K(S, S, S, S), boss: KG, marsh: true, night: true, plan: "S10_Kagachi", beat: "lower_the_sword",
                dialogue: L("KAGACHI|Three keys. One door. And a Kurogawa to open it. Your father would have been proud of the symmetry.",
                            "RENZO|My father would have cut you down before the first key.",
                            "KAGACHI|He tried.")),

            M(100, "EMBERLINE", T(Conversation, Exploration), Region.Dawn, Dawn,
                "The emotional conclusion. Not another wave.",
                "Leave the fortress.",
                "No combat at all: walking, the sunrise, and the last conversation.",
                "Renzo chose not to become Kagehira. Aiko sees the red thread on his wrist.",
                "Aiko: 'Where will you go?' Renzo: 'Home.' Aiko: 'There is no home.' Renzo looks toward Yorune. 'Then we'll build one.'",
                "Fade to black. END.",
                "There is no next mission. There is a home to build.",
                beat: "emberline_dawn",
                dialogue: L("AIKO|Where will you go?",
                            "RENZO|Home.",
                            "AIKO|There is no home.",
                            "RENZO|Then we'll build one.")),
        });

        /// <summary>Chapter, arc state and Seal stage follow from the mission number.</summary>
        private static CampaignMission[] Finish(CampaignMission[] all)
        {
            foreach (var m in all)
            {
                m.chapter = ChapterOf(m.id).number;
                m.renzo = m.id <= 20 ? RenzoState.Confused
                    : m.id <= 40 ? RenzoState.Angry
                    : m.id <= 60 ? RenzoState.Obsessed
                    : m.id <= 80 ? RenzoState.Consumed : RenzoState.Changed;
                m.seal = m.id <= 20 ? SealStage.Rumour
                    : m.id <= 40 ? SealStage.Hunted
                    : m.id <= 50 ? SealStage.Evidence
                    : m.id <= 60 ? SealStage.Protected
                    : m.id <= 70 ? SealStage.Witness
                    : m.id <= 80 ? SealStage.Assembled
                    : m.id <= 90 ? SealStage.Understood
                    : m.id <= 99 ? SealStage.Opened : SealStage.Chosen;
            }
            return all;
        }
    }
}
