using System.Collections.Generic;
using UnityEngine;

namespace Emberline.Core
{
    /// <summary>
    /// CharacterRig implementation for imported skinned characters (KayKit).
    /// Bridges the RigPose contract onto an Animator whose states are named
    /// after RigPose values ("Locomotion" + one state per pose), generated by
    /// EmberCharacterFactory. Scrubbed poses (AI ForcePose) drive states at
    /// speed 0 with explicit normalizedTime; one-shots play with a speed
    /// multiplier so any clip fits the requested gameplay duration.
    /// </summary>
    public class SkeletalRig : CharacterRig
    {
        [Header("Configured by EmberCharacterFactory")]
        public Color tint = Color.white;
        public bool ghost;
        public float ghostAlpha = 0.5f;
        public bool hasLantern;                 // Renzo's ember lantern + mood glow
        public string[] poseStates;             // indexed by (int)RigPose, may repeat
        public float[] poseClipLengths;         // clip length per pose, for speed fit

        private static readonly int MoveParam = Animator.StringToHash("Move");
        private static readonly int SpeedParam = Animator.StringToHash("AtkSpeed");
        private static readonly int LocomotionState = Animator.StringToHash("Locomotion");

        private Animator _anim;
        private readonly List<Renderer> _renderers = new();
        private readonly List<SkinnedMeshRenderer> _skinned = new();
        private MaterialPropertyBlock _mpb;
        private TrailRenderer[] _trails = System.Array.Empty<TrailRenderer>();
        private Light _lantern;
        private RigMood _mood = RigMood.Calm;

        // Hit-flash colour. Every solid character rests at tint == Color.white
        // (EmberCharacterFactory only authors a tint for ghosts), so the old
        // flash to Color.white multiplied albedo by 1 and was invisible. Hot
        // ember pushed past 1.0 reads under any lighting: lit faces blow out to
        // orange-white, shadowed faces still shift hue. Components stay <= 2
        // because Emberline/Surface declares _Color as fixed4, whose lowp range
        // on strict mobile drivers is -2..+2 (Ghost adds _Color, so it clamps
        // to a bright yellow-white there).
        private static readonly Color FlashColor = new(2f, 1.2f, 0.55f);
        private const float FlashDuration = 0.13f;

        private float _flashT;
        private bool _forcedThisFrame, _forcedActive;
        private RigPose _forcedPose;
        private float _forcedPhase;
        private bool _oneActive;
        private RigPose _onePose;
        private float _oneT, _oneDur;
        private bool _deadLatched;

        // Pooled Flicker after-images (no Instantiate/Destroy churn).
        private readonly List<AfterImage> _imagePool = new();
        private static Material _imageMat;
        private Color _authoredTint = Color.white;

        private void Awake()
        {
            _authoredTint = tint; // SetBaseColor overwrites `tint` when a boss enrages
            _anim = GetComponentInChildren<Animator>();
            _mpb = new MaterialPropertyBlock();
            GetComponentsInChildren(true, _renderers);
            GetComponentsInChildren(true, _skinned);
            // Every right-hand catalogue prop carries its own Trail child; only the
            // equipped one is active, so drive them all rather than caching first-found.
            _trails = GetComponentsInChildren<TrailRenderer>(true);
            if (ghost) ApplyGhostMaterials(ghostAlpha);
            else ApplyTint();
            if (hasLantern) BuildLantern();
            if (_anim != null) _anim.cullingMode = AnimatorCullingMode.CullUpdateTransforms;
        }

        /// <summary>Drives every cached trail. Emitting on an inactive prop is harmless,
        /// so no active-check is needed; the swapped-in weapon just picks it up.</summary>
        private void SetTrails(bool emitting)
        {
            for (var i = 0; i < _trails.Length; i++)
                if (_trails[i] != null) _trails[i].emitting = emitting;
        }

        // ------------------------------------------------------------ contract

        public override void PlayOneShot(RigPose pose, float duration)
        {
            if (_deadLatched) return;
            _oneActive = true;
            _onePose = pose;
            _oneT = 0f;
            _oneDur = Mathf.Max(0.05f, duration);
            if (_anim == null) return;
            var len = ClipLen(pose);
            _anim.SetFloat(SpeedParam, len / _oneDur);
            _anim.CrossFadeInFixedTime(StateName(pose), 0.05f, 0);
            if (pose == RigPose.Dead) _deadLatched = true;
        }

        public override void ForcePose(RigPose pose, float phase)
        {
            _forcedThisFrame = true;
            _forcedPose = pose;
            _forcedPhase = phase;
        }

        public override void Flash() => _flashT = FlashDuration;

        public override void MakeGhost(float alpha)
        {
            ghost = true;
            ghostAlpha = alpha;
            ApplyGhostMaterials(alpha);
        }

        public override void SetGhostAlpha(float a)
        {
            if (!ghost) return;
            ghostAlpha = a;
            if (_flashT <= 0f) ApplyTint();
        }

        public override void SetBaseColor(Color c)
        {
            tint = c;
            if (_flashT <= 0f) ApplyTint();
        }

        public override void SetMood(RigMood mood) => _mood = mood;

        public override void ResetVisuals()
        {
            // _deadLatched gates every PlayOneShot; a recycled rig that kept it
            // would spawn animation-frozen in its death pose.
            _deadLatched = false;
            _oneActive = false;
            _forcedThisFrame = false;
            _forcedActive = false;
            _flashT = 0f;
            SetTrails(false); // died mid-swing
            tint = _authoredTint;
            _mood = RigMood.Calm;
            ApplyTint();
        }

        public override void SpawnAfterImage()
        {
            if (_imageMat == null)
            {
                _imageMat = new Material(Shader.Find("Emberline/Ghost"));
                _imageMat.color = new Color(1f, 0.5f, 0.3f, 0.4f);
            }
            AfterImage img = null;
            foreach (var candidate in _imagePool)
                if (!candidate.Active) { img = candidate; break; }
            if (img == null)
            {
                if (_imagePool.Count >= 8) return; // cap
                img = new AfterImage(_skinned.Count, _imageMat);
                _imagePool.Add(img);
            }
            img.Capture(_skinned);
        }

        // -------------------------------------------------------------- drive

        private void Update()
        {
            var dt = Time.deltaTime;
            foreach (var img in _imagePool) img.Tick(dt);

            if (_flashT > 0f)
            {
                _flashT -= dt;
                if (_flashT <= 0f) ApplyTint();
                else SetAllColors(FlashColor, ghost ? Mathf.Min(1f, ghostAlpha + 0.3f) : 1f);
            }

            UpdateLantern(dt);
            if (_anim == null) return;

            if (_forcedThisFrame)
            {
                _forcedThisFrame = false;
                _oneActive = false;
                _forcedActive = true;
                if (_forcedPose == RigPose.Dead) _deadLatched = true;
                // Scrub: hold the state at an explicit normalized time.
                _anim.SetFloat(SpeedParam, 0f);
                _anim.Play(StateName(_forcedPose), 0, Mathf.Clamp01(_forcedPhase) * 0.98f);
                return;
            }

            if (_forcedActive)
            {
                // AI released the pose (state changed to Chase etc.) — resume.
                _forcedActive = false;
                if (!_deadLatched) _anim.CrossFadeInFixedTime(LocomotionState, 0.12f, 0);
            }

            if (_oneActive)
            {
                _oneT += dt;
                var phase = _oneT / _oneDur;
                SetTrails(_onePose is RigPose.Strike1 or RigPose.Strike2 or RigPose.Strike3 or RigPose.Cleave
                          && phase is > 0.1f and < 0.85f);
                if (_oneT >= _oneDur)
                {
                    _oneActive = false;
                    SetTrails(false);
                    if (!_deadLatched) _anim.CrossFadeInFixedTime(LocomotionState, 0.12f, 0);
                }
                return;
            }

            if (_deadLatched) return;
            _anim.SetFloat(MoveParam, move01, 0.07f, dt);
        }

        private string StateName(RigPose pose)
        {
            var i = (int)pose;
            return poseStates != null && i < poseStates.Length && !string.IsNullOrEmpty(poseStates[i])
                ? poseStates[i] : pose.ToString();
        }

        private float ClipLen(RigPose pose)
        {
            var i = (int)pose;
            return poseClipLengths != null && i < poseClipLengths.Length && poseClipLengths[i] > 0.01f
                ? poseClipLengths[i] : 1f;
        }

        // ----------------------------------------------------------- material

        private void ApplyTint() => SetAllColors(tint, ghost ? ghostAlpha : 1f);

        private void SetAllColors(Color c, float a)
        {
            _mpb.SetColor("_Color", new Color(c.r, c.g, c.b, a));
            foreach (var r in _renderers)
                if (r != null) r.SetPropertyBlock(_mpb);
        }

        /// <summary>Swap shaders to the translucent ghost look; color flows via MPB.</summary>
        private void ApplyGhostMaterials(float alpha)
        {
            var shader = Shader.Find("Emberline/Ghost");
            Material shared = null;
            foreach (var r in _renderers)
            {
                if (r == null) continue;
                var mats = r.sharedMaterials;
                var changed = false;
                for (var i = 0; i < mats.Length; i++)
                {
                    if (mats[i] != null && mats[i].shader == shader) continue;
                    shared ??= new Material(shader);
                    mats[i] = shared;
                    changed = true;
                }
                if (changed) r.sharedMaterials = mats;
                r.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            }
            SetAllColors(tint, alpha);
        }

        // ------------------------------------------------------------ lantern

        private void BuildLantern()
        {
            var anchor = FindDeep(transform, "spine") ?? FindDeep(transform, "torso") ?? transform;
            var go = new GameObject("EmberLantern");
            go.transform.SetParent(anchor, false);
            go.transform.localPosition = new Vector3(0.16f, 0.1f, -0.1f);
            _lantern = go.AddComponent<Light>();
            _lantern.type = LightType.Point;
            _lantern.range = 4.5f;
            _lantern.intensity = 1.4f;
            _lantern.color = new Color(1f, 0.55f, 0.3f);
            _lantern.shadows = LightShadows.None;
        }

        private void UpdateLantern(float dt)
        {
            if (_lantern == null) return;
            var (target, color) = _mood switch
            {
                RigMood.Enraged => (2.6f + Mathf.Sin(Time.time * 9f) * 0.8f, new Color(1f, 0.32f, 0.16f)),
                RigMood.Focused => (1.9f, new Color(1f, 0.48f, 0.26f)),
                _ => (1.3f + Mathf.Sin(Time.time * 2.1f) * 0.15f, new Color(1f, 0.58f, 0.32f)),
            };
            _lantern.intensity = Mathf.Lerp(_lantern.intensity, target, 1f - Mathf.Exp(-6f * dt));
            _lantern.color = Color.Lerp(_lantern.color, color, 1f - Mathf.Exp(-6f * dt));
        }

        private static Transform FindDeep(Transform root, string contains)
        {
            foreach (var t in root.GetComponentsInChildren<Transform>(true))
                if (t.name.ToLowerInvariant().Contains(contains)) return t;
            return null;
        }

        // --------------------------------------------------------- after-image

        /// <summary>One pooled baked-mesh snapshot of every skinned renderer.</summary>
        private class AfterImage
        {
            private readonly GameObject _root;
            private readonly MeshFilter[] _filters;
            private readonly Mesh[] _meshes;
            private readonly Material _mat;
            private float _life;

            public bool Active => _life > 0f;

            public AfterImage(int count, Material baseMat)
            {
                _root = new GameObject("FlickerImage");
                _root.SetActive(false);
                _mat = new Material(baseMat);
                _filters = new MeshFilter[count];
                _meshes = new Mesh[count];
                for (var i = 0; i < count; i++)
                {
                    var part = new GameObject("part");
                    part.transform.SetParent(_root.transform, false);
                    _filters[i] = part.AddComponent<MeshFilter>();
                    var mr = part.AddComponent<MeshRenderer>();
                    mr.sharedMaterial = _mat;
                    mr.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
                    _meshes[i] = new Mesh();
                }
            }

            public void Capture(List<SkinnedMeshRenderer> sources)
            {
                for (var i = 0; i < _filters.Length && i < sources.Count; i++)
                {
                    var src = sources[i];
                    if (src == null) continue;
                    src.BakeMesh(_meshes[i], true); // bake with scale applied
                    _filters[i].sharedMesh = _meshes[i];
                    _filters[i].transform.SetPositionAndRotation(src.transform.position, src.transform.rotation);
                    _filters[i].transform.localScale = Vector3.one;
                }
                _life = 0.28f;
                _root.SetActive(true);
            }

            public void Tick(float dt)
            {
                if (_life <= 0f) return;
                _life -= dt;
                if (_life <= 0f) { _root.SetActive(false); return; }
                var c = _mat.color;
                _mat.color = new Color(c.r, c.g, c.b, 0.4f * (_life / 0.28f));
            }
        }
    }
}
