using UnityEngine;

namespace Emberline.Core
{
    /// <summary>
    /// One of Renzo's blades. Assets live in Resources/Weapons (generated by the
    /// bootstrap) so the loadout can be resolved at runtime without scene wiring.
    /// </summary>
    [CreateAssetMenu(menuName = "Emberline/Weapon")]
    public class WeaponDef : ScriptableObject
    {
        public string id = "katana";
        public string displayName = "EMBER KATANA";
        [TextArea] public string blurb = "Balanced. The blade that guards the lantern.";
        public int unlockLevel;            // story level that must be cleared (0 = start)

        [Header("Strike chain")]
        public float[] strikeDamage = { 10f, 12f, 18f };
        public float strikeRange = 2.8f;
        public float strikeArcDeg = 130f;
        public float chainWindow = 0.75f;
        public float strikeAnimTime = 0.28f;
        public float lungeSpeed = 5.5f;

        [Header("Cleave")]
        public float cleaveDamage = 26f;
        public float cleaveRange = 3.3f;
        public float cleaveArcDeg = 170f;
        public float cleaveWindup = 0.24f;
        public float cleaveCooldown = 1.4f;

        [Header("Specials")]
        public bool parryOnPerfectDodge;   // Storm Tanto: perfect dodge staggers the attacker
        public bool pullOnThirdHit;        // Marsh Hook: hit 3 drags enemies in
        public bool poisonCleave;          // Marsh Hook: cleave leaves a poison puddle

        public Color trailColor = new(0.85f, 0.93f, 1f);
    }

    /// <summary>Selected/unlocked weapons, persisted in PlayerPrefs.</summary>
    public static class Loadout
    {
        private static WeaponDef[] _all;

        public static WeaponDef[] All =>
            _all ??= Resources.LoadAll<WeaponDef>("Weapons");

        public static bool IsUnlocked(WeaponDef w) =>
            w.unlockLevel <= 0 || Session.StoryUnlocked > w.unlockLevel;

        public static WeaponDef Current
        {
            get
            {
                var id = PlayerPrefs.GetString("weapon_sel", "katana");
                foreach (var w in All)
                    if (w.id == id && IsUnlocked(w)) return w;
                return All.Length > 0 ? All[0] : null;
            }
        }

        public static void Select(WeaponDef w)
        {
            PlayerPrefs.SetString("weapon_sel", w.id);
            PlayerPrefs.Save();
        }
    }
}
