using UnityEngine;

namespace Emberline.Core
{
    /// <summary>
    /// Broad weapon family. Drives the HUD label and the animation/prop choices;
    /// the numbers still live on the WeaponDef itself.
    /// </summary>
    public enum WeaponArchetype { Blade, Daggers, Thrown, Ranged }

    /// <summary>
    /// What the cleave button does for this weapon. Slash is the original arc;
    /// the rest let a weapon feel structurally different rather than just being
    /// the same swing with other numbers.
    /// </summary>
    public enum CleaveStyle { Slash, Spin, Ground, FanShot }

    /// <summary>
    /// One of Renzo's weapons. Assets live in Resources/Weapons (generated by the
    /// bootstrap) so the loadout can be resolved at runtime without scene wiring.
    /// </summary>
    [CreateAssetMenu(menuName = "Emberline/Weapon")]
    public class WeaponDef : ScriptableObject
    {
        public string id = "katana";
        public string displayName = "EMBER KATANA";
        [TextArea] public string blurb = "Balanced. The blade that guards the lantern.";
        public int unlockLevel;            // story level that must be cleared (0 = start)
        public WeaponArchetype archetype = WeaponArchetype.Blade;

        [Header("Hand props (KayKit names under Art/Characters/Props)")]
        /// <summary>Prop in the right hand; empty leaves that hand bare.</summary>
        public string propRight = "sword_1handed";

        /// <summary>Prop in the left hand — dual wielding, a quiver, a bomb pouch.</summary>
        public string propLeft = "";

        [Header("Strike chain")]
        /// <summary>Hits before the chain loops. Daggers run longer, heavier weapons shorter.</summary>
        public int strikeChainLength = 3;

        public float[] strikeDamage = { 10f, 12f, 18f };
        public float strikeRange = 2.8f;
        public float strikeArcDeg = 130f;
        public float chainWindow = 0.75f;
        public float strikeAnimTime = 0.28f;
        public float lungeSpeed = 5.5f;

        [Header("Cleave")]
        public CleaveStyle cleaveStyle = CleaveStyle.Slash;
        public float cleaveDamage = 26f;
        public float cleaveRange = 3.3f;
        public float cleaveArcDeg = 170f;
        public float cleaveWindup = 0.24f;
        public float cleaveCooldown = 1.4f;

        [Header("Specials")]
        public bool parryOnPerfectDodge;   // Storm Tanto: perfect dodge staggers the attacker
        public bool pullOnThirdHit;        // Marsh Hook: hit 3 drags enemies in
        public bool poisonCleave;          // Marsh Hook: cleave leaves a poison puddle

        [Header("Thrown slot")]
        /// <summary>Swap the kunai button for this weapon's own thrown ammunition.</summary>
        public bool replacesKunaiWithThrown;

        /// <summary>Resources/Props prefab name for that ammunition (falls back to Kunai).</summary>
        public string thrownId = "";

        public Color trailColor = new(0.85f, 0.93f, 1f);
    }

    /// <summary>Selected/unlocked weapons, persisted in PlayerPrefs.</summary>
    public static class Loadout
    {
        private static WeaponDef[] _all;

        public static WeaponDef[] All =>
            _all ??= Resources.LoadAll<WeaponDef>("Weapons");

        public static bool IsUnlocked(WeaponDef w) =>
            w.unlockLevel <= 0 || Session.StoryUnlocked > w.unlockLevel;

        public static WeaponDef Current
        {
            get
            {
                var id = PlayerPrefs.GetString("weapon_sel", "katana");
                foreach (var w in All)
                    if (w.id == id && IsUnlocked(w)) return w;
                return All.Length > 0 ? All[0] : null;
            }
        }

        public static void Select(WeaponDef w)
        {
            PlayerPrefs.SetString("weapon_sel", w.id);
            PlayerPrefs.Save();
        }
    }
}
